version: "3.2"
services:
  front:
    build: ./nginx/
#    image: poccciamatrsb/nginxama:v0.0.1
    deploy:
      placement:
        constraints: [node.role == manager]
    ports:
      - "80:80"
    volumes:
      - type: volume
        source: wpdata
        target: /var/www/html
#    environment:
#      - NGINX_HOST=foobar.com
#      - NGINX_PORT=80

  wordpress:
    build: ./wordpress/
#    image: poccciamatrsb/wpama:v0.0.1
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 150M
      restart_policy:
        condition: on-failure
    restart: always
    volumes:
      - type: volume
        source: wpdata
        target: /var/www/html
    environment:
      WORDPRESS_DB_PASSWORD: example

  mysql:
    image: mysql:5.7
    deploy:
      placement:
        constraints: [node.role == manager]
    restart: always
    volumes:
      - type: volume
        source: wpdb
        target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example

  redis:
    image: redis:5.0-rc5-alpine
    volumes:
      - type: volume
        source: wpredis
        target: /data
    deploy:
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          memory: 1024M
    command: redis-server --appendonly yes

volumes:
  wpdata:
  wpdb:
  wpredis:
